---
- name: Reiniciar contenedores Docker
  hosts: all
  become: true
  tasks:
    - name: Detener los contenedores
      docker_container:
        name: "{{ item }}"
        state: stopped
      with_items:
        - bazarr-subtitulos

    - name: Iniciar los contenedores
      docker_container:
        name: "{{ item }}"
        state: started
      with_items:
        - bazarr-subtitulos
